apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multicluster-controlplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multicluster-controlplane
    app.kubernetes.io/part-of: multicluster-controlplane
  name: multicluster-controlplane
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: multicluster-controlplane
    weight: 100
status: {}
