apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multicluster-controlplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multicluster-controlplane
    app.kubernetes.io/part-of: multicluster-controlplane
  name: multicluster-controlplane
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: multicluster-controlplane
status:
  loadBalancer: {}
